services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    ports:
      - '6380:6379'
    networks:
      - app_net
volumes:
  app_db_data:

networks:
  app_net:
    driver: bridge
