services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loyalty
      MYSQL_USER: loyalty-user
      MYSQL_PASSWORD: password
    # ports:
    #   - '3306:3306'
    volumes:
      - loyalty_db_data:/var/lib/postgresql/data
      - ./base-setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loyalty_net

  loyalty_backend:
    build: .
    container_name: loyalty_backend
    depends_on:
      - mysql
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_USER: loyalty-user
      DB_PASSWORD: password
      DB_NAME: loyalty
      DB_PORT: '5432'
    ports:
      - '3000:3000'
    networks:
      - loyalty_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - loyalty_backend
    networks:
      - loyalty_net

volumes:
  loyalty_db_data:

networks:
  loyalty_net:
    driver: bridge
