import { MigrationInterface, QueryRunner } from 'typeorm';

export class UserLogin1748936598155 implements MigrationInterface {
  name = 'UserLogin1748936598155';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "user_logins" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_at" TIME WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIME WITH TIME ZONE NOT NULL DEFAULT now(), "enable" boolean NOT NULL DEFAULT true, "deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "ipAddress" character varying, "userAgent" character varying, "provider" character varying, "user_id" integer, CONSTRAINT "PK_714c63a882ec975c5517f0f22a7" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_logins" ADD CONSTRAINT "FK_b0133215faede166e3c8772e0d2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "user_logins" DROP CONSTRAINT "FK_b0133215faede166e3c8772e0d2"`,
    );
    await queryRunner.query(`DROP TABLE "user_logins"`);
  }
}
